log:
  level: debug
bybit:
  ws_url: wss://stream.bybit.com/v5/public/linear
  trade_ws_url: wss://stream.bybit.com/v5/trade
  status_ws_url: wss://stream.bybit.com/v5/private
  trading_url: https://api.bybit.com
  api_key: 5audz0lEsFqIDQgQbN
  api_secret: zXKppDu7dxUT0LcVfGR0CmHwbIoNDabAFbuH
  symbol: ETHUSDT
  category: linear
  hedge_mode: false
order:
  quantity: 0.01
  spread_pct: .1
processor:
  requote_cooldown: 1
  requote_threshold: 0
injective:
  grpc_endpoint: ""
  chain_id: ""
  private_key: ""
  market_id: ""
  fee_payer_address: ""
  fee_denom: ""
  gas_price: 0