bybitOrderbook:
  ws_url: "wss://stream.bybit.com/v5/public/linear"
  symbol: "ETHUSDT"
  base_currency: "ETH"
  quote_currency: "USDT"

order:
  quantity: 1

injectiveExchange:
  network_name: "testnet"
  lb: "lb"
  priv_key: "5d386fbdbf11f1141010f81a46b40f94887367562bd33b452bbaa6ce1cd1381e"
  market_id: "0x54d4505adef6a5cef26bc403a33d595620ded4e15b9e2bc3dd489b714813366a"