market_id: "0x8a325bd4bd29e20eb182fbc6acca2224f5f4067a29e9feb44f60b01f8e5dd0f3"
subaccount_id: "0x18ac3db194e0f45fb4652766647e44c3388484ec000000000000000000000000"
AccountAddress: "inj1rzkrmvv5ur69ldr9yanxgljycvugfp8vdtc4yq"
bybit:
  api_key: "5audz0lEsFqIDQgQbN"      
  api_secret: "zXKppDu7dxUT0LcVfGR0CmHwbIoNDabAFbuH" 
  symbol: "ETHUSDT"
mongo_uri: mongodb+srv://sshft368:wrmNLr2AUkbA2Zy7@cluster0.eseeqov.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
telegram:
  bot_token: "7905115999:AAHy8nnCU33n7gbVMR81z312TFEbju1OIoY"
  channel_id: "-1002705562601"