# configs/bybittrader_config.yaml

log:
  level: debug # Log level: debug, info, warn, error

bybit:
  ws_url: wss://stream.bybit.com/v5/public/linear # Bybit USDT Perpetual Public WS URL (or other relevant WS URL)
  trading_url: https://api.bybit.com # Bybit REST API Base URL
  api_key: 5audz0lEsFqIDQgQbN  # Replace with your Bybit API Key
  api_secret: zXKppDu7dxUT0LcVfGR0CmHwbIoNDabAFbuH # Replace with your Bybit API Secret
  symbol: ETHUSDT # Trading symbol (e.g., ETHUSDT)
  category: linear # Trading category (e.g., linear, spot, inverse) - MUST MATCH YOUR ACCOUNT/SYMBOL TYPE

injective:
  # Injective config is not strictly needed for the Bybit Trader bot,
  # but keep the structure if your config.go expects it.
  # Remove or set to dummy values if only running the Bybit Trader.
  grpc_endpoint: ""
  chain_id: ""
  private_key: ""
  market_id: ""
  fee_payer_address: ""
  fee_denom: ""
  gas_price: 0

processor:
  requote_cooldown: 2 # Minimum seconds between quote updates
  requote_threshold: 0 # Percentage price change required to requote (0.1 = 0.1%)

order:
  quantity: 0.01 # Base quantity for quotes (e.g., 0.01 ETH)
  spread_pct: 50 # Desired spread percentage (e.0.05 = 0.05%)