# configs/config.yaml
bybit:
  ws_url: "wss://stream.bybit.com/v5/public/linear"
  symbol: "ETHUSDT"
injective:
  market_id: "0x54d4505adef6a5cef26bc403a33d595620ded4e15b9e2bc3dd489b714813366a"
  private_key: "YOUR_INJECTIVE_PRIVATE_KEY" # !! Replace with actual key or env var !!
order:
  quantity: 0.01
  spread_pct: 10.0
processor:
  requote_threshold: 0.0 # Percentage price change to trigger requote
  requote_cooldown: 1   # Seconds cooldown between requotes
log:
  level: "info" # debug, info, warn, error